# @name login
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Wojtek",
    "password": "password"
}

### Create blog

@authToken = {{login.response.body.token}}
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "AAAAAAAA999",
  "author": "Napisane",
  "url": "www.cos3.com",
  "likes": 44
}

### Delete blog

DELETE http://localhost:3003/api/blogs/69c7f7eacf761174ddeb3b18
Authorization: Bearer {{authToken}}

### Get all blogs

GET http://localhost:3003/api/blogs