POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5YzdmNDFlNTc2OWI3ZjdiNWFkNTNjZiIsImlhdCI6MTc3NDczMjcwMywiZXhwIjoxNzc0NzMyNzYzfQ.5ssbmWgnGZ0Lga5o67arpXAVJKspi8EGe8Zy2LGzvT4

{
  "title": "EEEEEEEEEE",
  "author": "Napisane",
  "url": "www.cos3.com",
  "likes": 44
}