GET http://localhost:3001/api/persons

### New person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "Mary Poppendieck",
"number": "39-23-6423122"
}
###
GET http://localhost:3001/api/persons